apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: irgccbvmk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/irgccbvmk-java-quarkus-gitops